services:
  - type: web
    name: tcl-pqrs
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: AIRTABLE_TOKEN
        sync: false
      - key: AIRTABLE_BASE
        value: appLVSEg1Y2zIwvuM
      - key: AIRTABLE_TABLE
        value: Pqrs
